[project]
name = "chess-explorer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.1",
    "psycopg[binary]>=3.3.2",
    "python-chess>=1.999",
]

[dependency-groups]
dev = [
    "ruff>=0.14.14",
]
